### PR TITLE
Add drawing features in drawutils

### PR DESCRIPTION
**Pull request by awth13**
## Rationale
Implements origin translation, rotation, and scaling for primitive shape drawing. Proposed as a draft because there are remaining issues, see [Further Comments](#Further-Comments).

## Testing
Compile and run `./tests/rotation.c`. **Note:** line clipping is disabled in this PR.

## Further Comments
I opened a PR now so you can see the general idea behind the implementation. The following issues have to be resolved. 

- [x] Doesn't work with ellipses. Need to update `ellipse()` function.
- [x] Sometimes lines have gaps or incorrect placement of pixels. I assume it has something to do with type casting.
- [x] Update tests and demos that use primitives to use new function signatures.
- [x] Improvements to the organisation of structs and `rotated_point()` function. Perhaps, maintaining a single `State` struct for all features would be cleaner.

### CODE REVIEW

**Comment by bolt-blue** [comment]
Really interesting.
Have had a first look through all of the commits.
Gonna dig in more soon.

Regarding elipses - it may be unrelated to your trouble with them, but I know I want to change the algorithm that draws them anyway; bit dodgy as I remember.

**Comment by awth13** [comment]
I improved the implementation of the global state keeping (colour, shade, etc.) and point rotation function. Also, replaced the line drawing algorithm with [Bresenham's algorithm](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm). The new algorithm does not use floating point numbers, which removes the rotated line weirdness I noticed earlier.

Any updates on the `ellipse()`?

**Comment by awth13** [comment]
I wrote a new ellipse algorithm -- turns out that when ellipses are not aligned with the coordinate axes, the equations get a bit more complicated. [This paper](https://cs.brown.edu/research/pubs/theses/masters/1989/dasilva.pdf) was very useful. It also contains other useful stuff regarding filling, clipping, and thick lines.

My work here is almost done, will complete today or tomorrow. Waiting for your comments.

**Comment by bolt-blue** [comment]
Sorry for being out of touch - got a bit crazy busy of late.
I will endeavor to dig into this soon.

**Comment by awth13** [comment]
No worries!

I am working on implementing rectangle rotation around the centre, for parity with ellipses. However, since it's out of scope for this PR, I'll mark it as ready for review.

**Comment by bolt-blue** [comment]
Well that was a crazy long time coming.
Can't believe how much time has passed.

Thanks for doing all of that!

I've no idea if I'll manage, but I do want to come back to this at some point and continue; there's still a lot of potential here, more thanks to you.

**Comment by awth13** [comment]
A lot of time has passed indeed! 

Let me know if you want to continue to work on this.

**Comment by bolt-blue** [comment]
I would like to continue, not exactly sure when, but if not soon (at least to _start_ something) then it may get forgotten, which would be sad.

I think it requires a real (if humble) project though - something to build with it.
That would help better shape it through usage.
Ideas?

**Pull request merged**
