### PR TITLE
Add flowers demo

### PR DESCRIPTION
**Pull request by awth13**
Hey!

I decided to play around with `termadore` this morning, had some fun with it, and got this demo as a result. It draws different [rose curves](https://en.wikipedia.org/wiki/Rose_(mathematics)). Nothing special but I got the basic gist of working with `termadore` and I think you will like it :)

**Note**
I updated the Makefile so that programs in `testing` can use `math.h`.

### CODE REVIEW

**Comment by bolt-blue** [comment]
Thanks - it's special to me at least.

Pulled it directly as it is, a test.
Thinking to move it to be a demo proper.

Should I perhaps set up 'demos' to have their own directory and follow the same `make` rules as 'tests'?

**Comment by awth13** [comment]
I put it in `testing` because it uses colours and colours are not in the main branch yet :)

I think putting demos in their own directory is a good idea. As a suggestion, I would even put `screen` in its own directory (`src` or `lib`). Makefiles in `testing` and `demos` then would include a Makefile from the top-level directory, with the top-level declaring common stuff only -- common flags to use, where the `SCREEN_LIB` is, etc. This way, users could stay in the directory they're working on.

**Comment by bolt-blue** [comment]
Thanks. I like the sound of that approach.
Will see if I can get it sorted.

**Comment by awth13** [comment]
Welcome! I have some other ideas but I'll keep them to myself for now. I enjoyed playing with `termadore` -- you made it really fun and easy to work with -- and thinking of contributing to the core (`screen`). If nothing else, I will open feature request issues.

**Comment by bolt-blue** [comment]
Appreciated :)
I'd happily take input on the core code.

1. I'm not massively happy with the approach, particularly regarding the current integration of colours - hence why it's still in its own branch.
2. I have some concern over the delta time - how and when it's calculated.

If nothing else, any raised issues/feature requests would be more than welcome.

**Comment by bolt-blue** [comment]
I'm trialling a different `make` config - currently in branch `alt-make`.
Not sure if it's quite what you were picturing.

I'm not overly satisfied, but it would be interesting to hear your thoughts.
Using this as a learning exercise.

**Comment by awth13** [comment]
Hey!

Sorry, busy week. Can you add me to friends on discord? A bit awkward discussing things on a merged PR.

**Pull request merged**
